### ISSUE TITLE
Index not in sync with desktop graphql schema

### ISSUE THREAD

**Issue by glitch-bch** [memocash/desktop#23]
I think the Index needs to be updated to match the new graphql schema introduced in last commit:

https://github.com/memocash/desktop/commit/8804cc02f405a4c0a17bbc241e75157fd910444f

I receive the error running on the latest Index server:

```
error with graphql response
[
  {
    message: 'Cannot query field "block" on type "Block".',
    locations: [ [Object] ],
    extensions: { code: 'GRAPHQL_VALIDATION_FAILED' }

```

**Comment by jchavannes** [comment]
Hey, thanks for trying out `desktop` with `index`!

The mater branch of the `index` repo is stale. Please try the `influx` branch, it is the most up to date right now. https://github.com/memocash/index/tree/influx

Feel free to message me on Telegram, I'd be really happy to hear about your experience!

**Comment by glitch-bch** [comment]
This fixes the issue! Thanks for the help. It's great to see such a cool dapp running on bitcoin!
